# Site settings
title: 'Arthur Nagy'
description: 'I work as an Android Technical Lead at HalcyonMobile.'
url: 'http://arthurnagy.me'
baseurl: ''
# google_analytics: 'UA-XXXXXX-X'
disqus_shortname: 'arthur-nagy'

author:
  name: 'Arthur Nagy'
  email: arthur.nagy@outlook.com
  twitter_username: arthur_nagy
  facebook_username: arthur.nagy.s
  instagram_username: arthurnagy
  medium_username: arthur.nagy
  github_username:  ArthurNagy
  linkedin_username:  nagyarthur

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
